### ISSUE TITLE
display: flex prefixing with Chrom 47 on iOS 8.4

### ISSUE THREAD

**Issue by yoadsn** [rofrischmann/inline-style-prefixer#72]
Hey,
Using these two UA strings reproduces a problem where 'display: flex" is not prefixed on chrome 47 with iOS 8.4 when it should be.
Safari on the same OS gets the prefix correctly.

```
var uaChrome = 'Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) CriOS/47.0.2526.107 Mobile/12H321 Safari/600.1.4';
var uaSafari = 'Mozilla/5.0 (iPad; CPU OS 8_4_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12H321 Safari/600.1.4';
```

I guess the problem stems from the fact that this OS forces chrome to use the native OS web view rendering.

Here is a CodePen with the repro in case needed.
http://codepen.io/anon/pen/YWLGaj
Let me know if any more info is required.

And thanks!

**Comment by rofrischmann** [comment]
Heyo. Would be helpful to get the information which `new Prefixer(uaChrome)._browserInfo` provides. Then it is kind of easy to actually find the problem. Thank you :P

**Comment by maxenglander** [comment]
I am having a similar issue with Chrome 47 on iOS 8. The user agent reported by `navigator.userAgent` is
> "Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B435 Safari/600.1.4"

    node> (new Prefixer("Mozilla/5.0 (iPhone; CPU iPhone OS 8_1_1 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B435 Safari/600.1.4"))._browserInfo
> { name: 'Chrome',
>  chrome: true,
>  version: 47,
>  webkit: true,
>  iphone: true,
>  ios: true,
>  osversion: 8.1,
>  mobile: true,
>  a: true,
>  prefix: { inline: 'Webkit', css: '-webkit-' },
  browser: 'ios_saf' }

However, I think the problem is that `_hasPropsRequiringPrefix` is set to false, where it should be true.

**Comment by rofrischmann** [comment]
So while we're running Chrome version 47, it actually is **always** based on the iOS-relative WebView right? So we should somehow 'mimic' the iOS Safari version. With @maxenglander's example that you would be `version: 8.1` instead of `version: 47`.

We should check if this is safe for every case and if yes, implement it.

**Comment by maxenglander** [comment]
@rofrischmann According to [this article](http://arstechnica.com/apple/2016/01/new-chrome-for-ios-is-finally-as-fast-and-stable-as-safari/), it appears that iOS forbids browsers to use any rendering engine other than the one afforded to apps by iOS. In the past, that was UIWebView. Currently (as Jan 2016 when that article was written), it is WKWebView. 

Since all browsers on iOS use the same rendering engine as Safari, it seems like it would be appropriate to apply `-webkit` prefixes at all times to browsers running on iOS whenever one would do the same for Safari.

**Comment by rofrischmann** [comment]
Seems like I finally got a convenient fix for this. Stay tuned, will release today :)

**Comment by maxenglander** [comment]
Hey @rofrischmann just wanted to check to see if a fix was released (but not apparent in this ticket), or if it's still pending. Thanks!

**Comment by rofrischmann** [comment]
Hey @maxenglander. I was working on sth. but actually couldn't finish it with all tests passing right now. I will try to fix this during next days as I have some time again.

**Comment by yoadsn** [comment]
Please note - updated the OP post to include a working pen (after changes to the dist filenames).
Problem persists with Master branch still. (2.0.1)

**Comment by yoadsn** [comment]
Awesome, Thanks a lot!
When do you think 2.0.2 would be released?

**Comment by rofrischmann** [comment]
Depends on whether my Macbook will ever be able to boot again or not. I just spilled some beer over it... Just cleaned the logic board and now its hopefully drying and working again :sweat_smile: 

Otherwise I'll try to pass permission or use another device to push the changes, but first lets wait another 1-2 days.
